notifications: 
  email:
    recipients:
      - chriswohlers@gmail.com
    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
language: node_js
node_js:
- '6'
# configure which branches to run
branches:
  # whitelist
  only:
    - travis
cache:
  directories:
    - node_modules
    - client/node_modules
script:
  - npm run dev
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  on: &2
    repo: hellobistro/hellobistro
    branch: travis
  bucket: hellostorage
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: hellostorage
  key: latest.zip
  bundle_type: zip
  application: hellobistro
  deployment_group: hellodeploy
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip