version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/hellobistro
hooks:
AfterInstall:
   - location: /home/ubuntu/hellobistro/bin/install-pkgs
     timeout: 1200
     runas: ec2-user
ApplicationStart:
   - location: /home/ubuntu/hellobistro/bin/app-start
     timeout: 60
     runas: ec2-user