version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/hellobistro
permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user
hooks:
AfterInstall:
   - location: bin/install-pkgs
     timeout: 1200
     runas: ec2-user
ApplicationStart:
   - location: bin/app-start
     timeout: 60
     runas: ec2-user